# Docs: <https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/customizing-dependency-updates>

version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: monthly }
    reviewers: [freifunkMUC/meshviewer]
    assignees: [freifunkMUC/meshviewer]

  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
    reviewers: [freifunkMUC/meshviewer]
    assignees: [freifunkMUC/meshviewer]
